name: Robot Framework Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        run: echo Fazendo checkout do repositorio
        uses: actions/checkout@v2

      - name: Set up Python
        run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - echo "Instalação das depedências do Projeto"
      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: echo Executando os testes de API do Robot
        run: |
          robot --outputdir results/ tests/
      
      - name: Test Report
        run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/**