name: Robot Framework Tests

on: push 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        # run: echo Fazendo checkout do repositorio
        uses: actions/checkout@v2

      - name: Set up Python
        # run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        # run: echo Instalação das depedências do Projeto
        run: |
          echo Instalação das depedências do Projeto
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        # run: echo Executando os testes de API do Robot
        run: |
          robot --outputdir results/ tests/
      
      - name: Test Report
        # run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: results/
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: results/
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
